name: Seeworthy
favicon: null
layout_spectrum: 0.8526558487210423
typography_spectrum: 0.20932295476086438
title: Creating desire
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.2754141753539443
  lightness: 0.6256853223312646
  saturation: 0.9308702677953988
  rhythmicContrast: 0.6216855477541685
purpose: []
