name: Seeworthy
favicon: null
layout_spectrum: 0.50334
typography_spectrum: 0.65526
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Creating desire
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fcdda4'
    - '#96380b'
    - '#ba8b3b'
    - '#faa72a'
  brandStrength: 0.625
  lightness: 0.4375
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
