name: Seeworthy
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2093229547608644
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Creating desire
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0C0C0D'
    - '#4B4130'
    - '#FFFFF3'
    - '#B4916E'
    - '#1D5CFF'
  brandStrength: 0.1379928
  lightness: 0.6256853223312646
  saturation: 0.9308702677953988
  rhythmicContrast: 0.6216855477541685
purpose: []
